name: Async build
# This checks if we can compile and then tests/builds at the same time. If build and test pass, it pushes the image. 'Harder' but faster overall.
on:
  workflow_call:
    outputs:
      changed:
        description: 'True if pipeline passes'
        value: ${{ jobs.changes.outputs.changed }}
    inputs:
      image-name:
        description: 'The base name of the image'
        required: true
        default: 'canary'
        type: string
      tag:
        description: 'The tag of the image'
        required: true
        default: 'latest'
        type: string

jobs:
  changes:
    name: Preflight checks
    uses: Projectweek-2022-2023/workflows/.github/workflows/check-changes.yml@main
    secrets: inherit
  
  testing:
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    uses: Projectweek-2022-2023/workflows/.github/workflows/test-mvn.yml@main
    secrets: inherit

  build-candidate:
    needs: changes
    if: ${{ needs.changes.outputs.changed == 'true' }}
    uses: Projectweek-2022-2023/workflows/.github/workflows/build-candidate.yml@main
    secrets: inherit
    with:
      image-name: candidate
      tag: ${{ github.sha }}

  publish-candidate:
    name: relabeling and pushing candidate to latest
    needs: [testing, build-candidate]
    uses: Projectweek-2022-2023/workflows/.github/workflows/relabel-image.yml@main
    secrets: inherit
    with:
      image-name: ${{ inputs.image-name }}
      tag: ${{ inputs.tag }}

  housekeeping:
    name: housekeeping
    needs: [build-candidate, publish-candidate] #always happens, we just need to wait for these to wrap up
    if: always() #assuming we can't delete stuff with the token, we're just gonna push a hello-world image over it since it's only 11kb
    uses: Projectweek-2022-2023/workflows/.github/workflows/housekeeping.yml@main
    secrets: inherit
