name: Building and pushing image

on:
  workflow_call:
    outputs:
      changed:
        description: 'True if passed, false otherwise'
        value: ${{ jobs.build-image.outputs.passed }}
    inputs:
      image-name:
        description: 'The base name of the image'
        required: true
        default: 'candidate'
        type: string
      tag:
        description: 'The tag of the image'
        required: true
        default: 'latest'
        type: string
      
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.REPO }}/${{ inputs.image-name }}:${{ inputs.tag }}
            ghcr.io/${{ env.REPO }}/${{ inputs.image-name }}:latest

      - name: return when tests fail
        if: ${{ failure() }}
        run: |
          echo "::set-output name=passed::false"
      - name: return when tests pass
        if: ${{ success() }}
        run: |
          echo "::set-output name=passed::true"