name: Generating caches
on:
  workflow_call:
    outputs:
      changed:
        description: 'True if passed, false otherwise'
        value: ${{ jobs.test.outputs.passed }}

jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      # - name: Cache local Maven repository
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #       ${{ runner.os }}-maven-
      - name: Building project to get the cache
        run: mvn -B install --file pom.xml -DskipTests
      - name: return when tests pass
        if: ${{ success() }}
        run: |
          echo "::set-output name=passed::true"
      - name: return when tests fail
        if: ${{ failure() }}
        run: |
          echo "::set-output name=passed::false"