name: Generating caches
on:
  workflow_call:
    outputs:
      changed:
        description: 'True if passed, false otherwise'
        value: ${{ jobs.generate-cache.outputs.passed }}

jobs:
  generate-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: copy dummy file
        run: |
          cp .github/helpers/dummy_secret.java src/main/java/util/Secret.java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Building project to get the cache
        run: mvn -B install --file pom.xml -DskipTests
      - name: return when cache is built
        if: ${{ success() }}
        run: |
          echo "::set-output name=passed::true"
      - name: return when cache isnt built
        if: ${{ failure() }}
        run: |
          echo "::set-output name=passed::false"