name: Relabeling image

on:
  workflow_call:
    outputs:
      changed:
        description: 'True if passed, false otherwise'
        value: ${{ jobs.housekeeping.outputs.passed }}
      
jobs:
  housekeeping:
    runs-on: ubuntu-latest
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: cleaning up 
        uses: actions/delete-package-versions@v3
        with: 
          package-name: 'candidate'
          min-versions-to-keep: 3
        
      - name: return when fail
        if: ${{ failure() }}
        run: |
          echo "::set-output name=passed::false"
      - name: return when pass
        if: ${{ success() }}
        run: |
          echo "::set-output name=passed::true"