name: cleaning up the mess
on:
  workflow_call:
    outputs:
      changed:
        description: 'True if passed, false otherwise'
        value: ${{ jobs.housekeeping.outputs.passed }}

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: housekeeping
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          # NOTE: at now only orgs is supported
          owner: ${{ github.repository_owner }}
          name: ${{ env.REPO_NAME }}/candidate
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{github.sha}}
        
      - name: return when fail
        if: ${{ failure() }}
        run: |
          echo "::set-output name=passed::false"
      - name: return when pass
        if: ${{ success() }}
        run: |
          echo "::set-output name=passed::true"