name: Running selenium tests

on:
  workflow_call:
    outputs:
      changed:
        description: 'True if tests passed, false otherwise'
        value: ${{ jobs.test.outputs.passed }}

jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      - name: Build Dockerfile 
        run: docker build . --file=.github/DockerTest -t cicd:test #This is the dockerfile that will be used for testing, it's literally just coping the war into a tomcat image and running it, probably not the best way to do it but it works
      - name: Run Dockerfile
        run: docker run -d -p 8080:8080 cicd:test
      - name: Run tests
        run: xvfb-run mvn test
      - name: Publish Test Report
        if: ${{ failure() }}
        uses: scacap/action-surefire-report@v1
      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Tested war
          path: target/*.war
          retention-days: 1
      